### ISSUE TITLE
Complete randomly I receive SocketExceptions

### ISSUE THREAD

**Issue by JSCProjects** [wl-online-payments-direct/sdk-dotnet#6] opened 2023-09-20 09:26 UTC
Complete randomly I receive SocketExceptions when I call the clients (Test Environment). Some test runs complete without failure, but most give a SocketException. In Azure App Insights I see that it generally takes 9sec when the exception is thrown.

FYI this is the stack trace we received:

```
OnlinePayments.Sdk.CommunicationException:
   at OnlinePayments.Sdk.DefaultImpl.DefaultConnection+<SendHttpMessage>d__4`1.MoveNext (OnlinePayments.Sdk, Version=3.20.0.0, Culture=neutral, PublicKeyToken=null)
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw (System.Private.CoreLib, Version=6.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e)
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess (System.Private.CoreLib, Version=6.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification (System.Private.CoreLib, Version=6.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e)
   at OnlinePayments.Sdk.DefaultImpl.DefaultConnection+<SendHttpMessage>d__3`1.MoveNext (OnlinePayments.Sdk, Version=3.20.0.0, Culture=neutral, PublicKeyToken=null)
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw (System.Private.CoreLib, Version=6.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e)
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess (System.Private.CoreLib, Version=6.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification (System.Private.CoreLib, Version=6.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e)
   at OnlinePayments.Sdk.DefaultImpl.DefaultConnection+<Get>d__7`1.MoveNext (OnlinePayments.Sdk, Version=3.20.0.0, Culture=neutral, PublicKeyToken=null)
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw (System.Private.CoreLib, Version=6.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e)
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess (System.Private.CoreLib, Version=6.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification (System.Private.CoreLib, Version=6.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e)
   at OnlinePayments.Sdk.Communicator+<Get>d__23`1.MoveNext (OnlinePayments.Sdk, Version=3.20.0.0, Culture=neutral, PublicKeyToken=null)
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw (System.Private.CoreLib, Version=6.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e)
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess (System.Private.CoreLib, Version=6.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification (System.Private.CoreLib, Version=6.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e)
   at OnlinePayments.Sdk.Merchant.HostedCheckout.HostedCheckoutClient+<GetHostedCheckout>d__2.MoveNext (OnlinePayments.Sdk, Version=3.20.0.0, Culture=neutral, PublicKeyToken=null)
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw (System.Private.CoreLib, Version=6.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e)
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess (System.Private.CoreLib, Version=6.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification (System.Private.CoreLib, Version=6.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e)
   at Deftpower.Dms.PaymentService.Worldline.HostedCheckoutPage.WorldlineHostedCheckoutPagePaymentService+<GetMandateFromExternalAndMerge>d__11.MoveNext (Deftpower.Dms.PaymentService.Worldline.HostedCheckoutPage, Version=7.5.2.0, Culture=neutral, PublicKeyToken=null: /azp/_work/40/s/src/Deftpower.Dms.PaymentService.Worldline.HostedCheckoutPage/WorldlineHostedCheckoutPagePaymentService.cs:170)
```

**Comment by online-payments-support-team** [comment] 2023-09-21 16:02
Hello @JSCProjects,

Thank you for reporting the issue and we had a closer look in order to find the possible cause. The CommunicationException thrown in this case states that the possible cause for this issue might be an error in the communication with the payment platform. Maybe additional information in the logs is being stored and it can give us more information about the origin. 

There are three possible Exceptions that can cause this CommunicationException to be raised:

```
- System.Net.Http.HttpRequestException: A base class for exceptions thrown by the System.Net.Http.HttpClient and System.Net.Http.HttpMessageHandler classes
- System.Threading.Tasks.TaskCanceledException: Represents an exception used to communicate task cancellation.
- System.Net.WebException: The exception that is thrown when an error occurs while accessing the network through a pluggable protocol.
```

If you can provide us with more information in the logs we should be able to identify which exactly is causing this error but seem like that might be a connection issue with the platform.

Let us know if this information is helpful.

**Comment by JSCProjects** [comment] 2023-09-22 11:29
Hello @online-payments-support-team,

I've tried to find any information in your portal, but I can't find anything. The new portal does not contain any information about these things from a developer point of view. In the legacy portal there is also no information or I'm looking at the wrong  places. I completely followed all the [guidelines](https://docs.direct.worldline-solutions.com/en/integration/how-to-integrate/server-sdks/dotnet). The connection is disposed and before CloseExpiredConnections(but on your code there is no implementation) is called. But still connections are randomly closed.

Thanx in advance.

**Comment by online-payments-support-team** [comment] 2023-09-22 14:51
Hello @JSCProjects,

We appreciate your feedback regarding the lack of information available on our documentation portal related to the connection issues you have. We are continuously working to improve the portal and make the documentation more complete and closer to the parties included in the integration process.

In order to figure out what can be the possible cause we would be very grateful if you can provide us with some code samples or logs so we can further investigate. We are eager to help you resolve this issue and therefore looking forward to your response.

Apologies for any inconvenience caused during the integration process and we are committed to resolving this issue promptly.

Kind regards

**Comment by online-payments-support-team** [comment] 2023-10-27 06:03
Hello @JSCProjects,

We haven't received any feedback for a longer period from your side and therefore we are closing this issue. 
If you still experience the issue with the SDK we encourage you to report it again and provide any relevant details that can help us narrow down the cause. 

Kind regards

**Comment by JSCProjects** [comment] 2023-10-27 06:06
Because it has changed major version I had to do some more changes to the code and currently don't have the time to check it. Hopefully next week!

**Closed** 2023-10-27 06:06 UTC
