### ISSUE TITLE
SocketExceptions in Azure App Service due to the way HttpClient is used

### ISSUE THREAD

**Issue by bennycoomans** [wl-online-payments-direct/sdk-dotnet#9] opened 2024-02-23 13:54 UTC
For one of our customers, we recently implemented the payment flow using this SDK. Just like the reporter of #6, we ran into SocketExceptions when running our ASP.Net Core web application in an Azure App Service. These exceptions had the same stack trace as in that issue (except of course for the last line, referring to the app the SDK was implemented in).

I was able to find the cause of this issue. The error is in [this line](https://github.com/wl-online-payments-direct/sdk-dotnet/blob/50721b98b14f16bf64611ef0044681efaafc2a1f/OnlinePayments.Sdk/DefaultImpl/DefaultConnection.cs#L39C1-L40C1). The code says `_httpClient = new HttpClient(handler)`. However, this is not how `HttpClient` is supposed to be used. I found a blog post that probably explains it better than I can, so please see https://www.milanjovanovic.tech/blog/the-right-way-to-use-httpclient-in-dotnet. You may also want to check out the official documentation: https://learn.microsoft.com/en-us/dotnet/architecture/microservices/implement-resilient-applications/use-httpclientfactory-to-implement-resilient-http-requests#issues-with-the-original-httpclient-class-available-in-net. The short version of the explanation is that using a lot of `HttpClient` instances will cause port exhaustion, but it is also not recommended to use a single `HttpClient` instance for a long time, because that will prevent DNS changes from being processed.

These links contain several suggestions to fix this issue. Some of them only apply to .Net Core / .NET 5+, and not to the .Net Framework. Because your SDK supports both versions of .Net, the best fix would probably be to introduce a way to use `IHttpClientFactory`, as suggested in the official documentation on https://learn.microsoft.com/en-us/dotnet/fundamentals/networking/http/httpclient-guidelines#recommended-use as the recommended way to use HttpClient on the .Net Framework.

The way I fixed the issue in our application is by applying the following change to our code. Note that I left out most of the code for the class `HttpClientFactoryConnection`, because it is equivalent to the code in `DefaultConnection`, so I only supplied the parts where there are relevant changes compared to `DefaultConnection`.

```
/* Old */

var client = Factory.CreateClient(configuration.ApiKey, configuration.ApiSecret, configuration.ApiEndpoint, configuration.PspId);

/* New */

var config = Factory.CreateConfiguration(configuration.ApiKey, configuration.ApiSecret, configuration.ApiEndpoint, configuration.PspId);
        var metaDataProvider = new MetaDataProviderBuilder(config.Integrator).WithShoppingCartExtension(config.ShoppingCartExtension).Build();
        var communicator = new CommunicatorBuilder()
            .WithApiEndpoint(configuration.ApiEndpoint)
            .WithConnection(new HttpClientFactoryConnection(httpClientFactory, config.SocketTimeout))
            .WithAuthenticator(new DefaultAuthenticator(config.AuthorizationType, config.ApiKeyId, config.SecretApiKey))
            .WithMarshaller(DefaultMarshaller.Instance)
            .WithMetaDataProvider(metaDataProvider)
            .Build();
        var client = Factory.CreateClient(communicator);

public class HttpClientFactoryConnection : IConnection
{
    private const string XRequestIdHeader = "X-Request-Id";
    private static readonly TimeSpan DefaultSocketTimeout = TimeSpan.FromSeconds(10);

    private readonly IHttpClientFactory httpClientFactory;
    private readonly TimeSpan? socketTimeout;
    private ICommunicatorLogger? communicatorLogger;

    public HttpClientFactoryConnection(IHttpClientFactory httpClientFactory, TimeSpan? socketTimeout)
    {
        this.httpClientFactory = httpClientFactory;
        this.socketTimeout = socketTimeout;
    }

    ...

    private async Task<T> SendHttpMessage<T>(HttpMethod method, Uri uri, IEnumerable<IRequestHeader> requestHeaders,
        Func<HttpStatusCode, Stream, IEnumerable<IResponseHeader>, T> responseHandler, HttpContent? content, string? contentString)
    {
            ...
            using var httpClient = httpClientFactory.CreateClient();
            httpClient.Timeout = socketTimeout ?? DefaultSocketTimeout;
            using var httpResponse = await httpClient.SendAsync(message);
            ...
}
```

After deploying the application with this change, no more SocketExceptions were thrown, so I am convinced that this is a good solution for this issue. Even though our application works fine now, I would like to see this issue fixed in the SDK. For other users of the SDK, but also to be able to remove as much custom code as possible from our application. When you make a change in `DefaultConnection` now, we would have to be check that file on each release of the SDK and manually apply any changes to our `HttpClientFactoryConnection`.

I can imagine that you might want to avoid breaking changes, to prevent other users of the library from having to change their code when updating the library. However, I think that the breaking change is worth it, because customers might run into this issue without knowing about it beforehand, or even suffer from it without knowing it if their logging is under par. But if you really want to support the old way, I can understand that. But I would appreciate it if this could be fixed in a way that allows us to initialize the SDK with one line again, instead of having to call methods like `WithAuthenticator` and `WithMarshaller` manually. Perhaps by introducing another `Factory` overload `public static IClient CreateClient(string apiKeyId, string secretApiKey, Uri apiEndpoint, String integrator, IHttpClientFactory httpClientFactory)`, that we can call like this, so we don't have to specify the other default implementations:
```
var client = Factory.CreateClient(configuration.ApiKey, configuration.ApiSecret, configuration.ApiEndpoint, configuration.PspId, httpClientFactory);
```

A more or less backwards-compatible way for you to implement this could be by adding another interface, e.g. `IHttpClientProvider` with a method `CreateClient`, that is passed to the constructor of `DefaultConnection`. A default implementation `DefaultHttpClientProvider` could then be made, which just returns a new `HttpClient` instance, while an implementation `FactoryHttpClientProvider` could be created that takes an `IHttpClientFactory` in its constructor and returns the result of `httpClientFactory.CreateClient()`. This would only be backwards-incompatible for users who create `DefaultConnection` directly, but I think that the amount of users who have done that is limited. Even if you would not supply the `FactoryHttpClientProvider` class in the SDK, this would already be a helpful change for us, because the implementation of that class is trivial, but we would at least be able to re-use `DefaultConnection` instead of copying all of its contents.

Another solution could be to introduce a `FactoryConnection` (name pending ;) ) class that implements `IConnection` and keep that next to `DefaultConnection`. But they would be almost the same. They could of course share a base class with all common code. In this scenario, an overload `public static IClient CreateClient(string apiKeyId, string secretApiKey, Uri apiEndpoint, String integrator, IHttpClientFactory httpClientFactory)` could instantiate a `FactoryConnection` instead of a `DefaultConnection`. This would be a 100% backwards compatible solution.

I hope I supplied you with enough information to understand the problem and be able to fix it. Please let me know if you have any questions.

**Comment by worldline-direct-support-team** [comment] 2024-02-23 14:54
Hello @bennycoomans,

Thank you for your valuable feedback and the detailed explanation of the issue you are facing. We sincerely appreciate your suggestions for resolving this matter, and we will thoroughly investigate this topic to determine the most optimal solution. We understand the importance of maintaining backwards compatibility, and we will explore all available possibilities to address this concern.

We will keep you informed of our progress and provide you with feedback once we have completed our research and analysis.

Best regards,
Worldline Online Payments Support Team

**Comment by JSCProjects** [comment] 2024-03-01 08:25
I would also like to see a way ootb to use the `IHttpClientFactory`.

**Comment by worldline-direct-support-team** [comment] 2024-03-11 09:30
Hello @bennycoomans,

After conducting a thorough investigation into the reported issue, we have determined that extending the `DefaultConnection` class is the most optimal solution at this time. This approach ensures backward compatibility of the SDK while also enabling the usage of the `IHttpClientFactory`. We will introduce an additional constructor that accepts a delegate function, allowing users to have control over the creation of the `HttpClient` within the `DefaultConnection` class.

Here is an example code snippet demonstrating how this extension can be utilised:

```
var config = Factory.CreateConfiguration("", "");

// Create a function that handles the creation of the `HttpClient`
Func<HttpClient> provider = () =>
{
    var httpClient = httpClientFactory.CreateClient();
    httpClient.Timeout = config.SocketTimeout;
    return httpClient;
};

// Create a communicator by providing the function for handling the creation of the `HttpClient` to the `DefaultConnection` instance
var communicator = Factory.CreateCommunicatorBuilder(config)
    .WithConnection(new DefaultConnection(provider))
    .Build();

// Create a client
var client = Factory.CreateClient(communicator);
```

This extension provides users with the flexibility to have control over the creation of the `HttpClient`, thereby enhancing resiliency in scenarios where such control is necessary.

We believe that this extension will effectively resolve the reported issue and enable users to better utilise the capabilities of the SDK.

Kind regards
Worldline Online Payments Support Team

**Comment by worldline-direct-support-team** [comment] 2024-04-02 16:42
Hello @bennycoomans,

We would like to inform you about the recent updates made to the DefaultConnection class extension in the newly released SDK version 3.26.0. These changes include the addition of a delegate function.

If you have any questions or comments regarding this solution, please don't hesitate to reach out to us. Our dedicated support team is available to assist you.

Kind regards
Worldline Online Payments Support Team

**Comment by bennycoomans** [comment] 2024-04-19 07:44
Hi @worldline-direct-support-team,

Thank you for your changes. I am now using them successfully to create a HttpClient through `IHttpClientFactory` and passing it to `DefaultConnection`.

However, I feel like the implementation is not entirely complete. The `DefaultConnection` constructor has also been given a parameter `Action disposeAction = null`. I think that that is supposed to be used to dispose any stuff, like the `HttpClient`, that is created by the `Func<HttpClient> httpClientProvider`. But the created `HttpClient` is not accessible from that `Action`. I see that using this action works for `HttpClient` instances that are created when the consumer is not supplying their own factory, because you simply do `_disposeAction = httpClient.Dispose;`. But in my case, I would expect to be able to access the created `HttpClient`, so I can properly dispose it. E.g. by being able to pass a parameter `Action<HttpClient> httpClientDisposeAction`, which is then called in a `finally` block after `var httpClient = _httpClientProvider();`:

```
                    var httpClient = _httpClientProvider();
                    try
                    {
                        var httpResponseTask = httpClient.SendAsync(message)
                            .ConfigureAwait(false);

                        using (var httpResponse = await httpResponseTask)
                        {
                            ...
                        }
                    }
                    finally
                    {
                        _httpClientDisposeAction(httpClient);
                    }

```

For `_httpClientDisposeAction` you could also assign a default action that does nothing with the `httpClient`, so consumers that wish to re-use a HttpClient are not affected. But in my case, where I let `IHttpClientFactory` create a new `HttpClient` for every call, I could pass `(httpClient) => httpClient.Dispose`.

**Comment by bennycoomans** [comment] 2024-04-19 12:53
Hi @worldline-direct-support-team,

On first glance, the code changes look good 👍. However, the new version is not in the NuGet repository (https://www.nuget.org/packages/OnlinePayments.Sdk) yet. I also noticed that version 3.27.0, which was released 3 days ago, is not on NuGet either. Can you look into this?

**Comment by worldline-direct-support-team** [comment] 2024-04-20 10:37
Hey @bennycoomans,

We would like to apologise for the inconvenience caused by the unavailability of the artifacts on the NuGet repository. Our team is actively working on resolving this issue and we assure you that both versions 3.27.0 and 3.27.1 will be published once the issue is resolved.

We understand the importance of timely updates and we will keep you informed as soon as this issue is resolved. Thank you for your understanding and patience.

Kind regards
Worldline Online Payments Support Team

**Comment by bennycoomans** [comment] 2024-06-13 15:51
Hi! Is there any update about the NuGet repository? I saw that you just released 3.28.0, but the latest version in the NuGet repository (https://www.nuget.org/packages/OnlinePayments.Sdk) is still 3.26.0.

**Comment by worldline-direct-support-team** [comment] 2024-07-04 10:05
Hello @bennycoomans,

We are pleased to inform you that the previously reported issue concerning the NuGet repository has been successfully resolved. The missing artifacts have now been successfully published on NuGet.

We would like to express our sincere gratitude for your patience and understanding throughout the process. We remain committed to providing seamless services and deeply regret any inconvenience this incident may have caused to your operations.

Kind regards,
Worldline Online Payments Support Team

**Closed by worldline-direct-support-team** 2024-07-04 10:05 UTC

**Comment by bennycoomans** [comment] 2024-07-04 10:59
Thanks, indeed I see the new versions in the NuGet repository now 👍
